version: '3.8'

services:
  # WordPress
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./wp-otel-metrics:/var/www/html/wp-content/plugins/wp-otel-metrics
      - wordpress_data:/var/www/html
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql

  # Jaeger for OpenTelemetry
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"   # Jaeger agent
      - "6832:6832/udp"   # Jaeger agent
      - "5778:5778"       # Serve configs
      - "16686:16686"     # Jaeger UI
      - "4317:4317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP
      - "14250:14250"     # gRPC
      - "14268:14268"     # Accept jaeger.thrift over HTTP
      - "14269:14269"     # Admin port
      - "9411:9411"       # Zipkin compatible endpoint
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      COLLECTOR_OTLP_ENABLED: true

  # Optional: Zipkin (alternative to Jaeger)
  # zipkin:
  #   image: openzipkin/zipkin:latest
  #   ports:
  #     - "9411:9411"

volumes:
  wordpress_data:
  mysql_data: